### PR TITLE
.gitignore, UIColor+BFW, placeholder image

### PR DESCRIPTION
**Pull request by tomj**

### CODE REVIEW

**Comment by tomj** [comment]
This has conflicts, and it's 3.5 years old so it _probably_ should be closed

**Comment by barefeettom** [comment]
Thanks Tom. I think, from memory, that I absorbed some of your changes but not all.

**Comment by tomj** [comment]
All good - I was actually recommending `BFWDrawView` to someone today and dropped by here to see what was happening with it :)

Is this the primary repo or is BitBucket the source of truth these days? (note: nowunlimited free repos on GitHub if that was your reasoning for using BitBucket in the past).

**Comment by barefeettom** [comment]
BFWDrawView is still alive and active. Swift 4.2 etc. It's mirrored on both Bitbucket and GitHub.

I've spent more time lately on BFWControls:
http://github.com/BareFeetWare/BFWControls/
http://bitbucket.org/BareFeetWare/BFWControls/

**Pull request closed without merging**
